git clone https://github.com/dreamcity-rp/fivem-appearance.git resources/[dc]/[core]/fivem-appearance &&
git clone https://github.com/dreamcity-rp/dc-hud.git resources/[dc]/[core]/dc-hud &&
git clone https://github.com/dreamcity-rp/ox_fuel.git resources/[dc]/[core]/ox_fuel &&
git clone https://github.com/dreamcity-rp/dc-weathersync.git resources/[dc]/[core]/dc-weathersync &&
git clone https://github.com/dreamcity-rp/dc-spawn.git resources/[dc]/[core]/dc-spawn &&
git clone https://github.com/dreamcity-rp/dc-smallresources.git resources/[dc]/[others]/dc-smallresources &&
git clone https://github.com/dreamcity-rp/dc-skillbar.git resources/[dc]/[others]/dc-skillbar &&
git clone https://github.com/dreamcity-rp/dc-recyclejob.git resources/[dc]/[activities]/dc-recyclejob &&
git clone https://github.com/dreamcity-rp/dc-prison.git resources/[dc]/[others]/dc-prison &&
git clone https://github.com/dreamcity-rp/dc-policejob.git resources/[dc]/[activities]/[jobs]/[private]/dc-policejob &&
git clone https://github.com/dreamcity-rp/dc-multicharacter.git resources/[dc]/[core]/dc-multicharacter &&
git clone https://github.com/dreamcity-rp/dc-menu.git resources/[dc]/[core]/dc-menu &&
git clone https://github.com/dreamcity-rp/dc-management.git resources/[dc]/[core]/dc-management &&
git clone https://github.com/dreamcity-rp/dc-loading.git resources/[dc]/[core]/dc-loading &&
git clone https://github.com/dreamcity-rp/dc-interior.git resources/[dc]/[core]/dc-interior &&
git clone https://github.com/dreamcity-rp/dc-input.git resources/[dc]/[core]/dc-input &&
git clone https://github.com/dreamcity-rp/dc-core.git resources/[dc]/[core]/dc-core &&
git clone https://github.com/dreamcity-rp/dc-commandbinding.git resources/[dc]/[core]/dc-commandbinding &&
git clone https://github.com/dreamcity-rp/dc-cityhall.git resources/[dc]/[others]/dc-cityhall &&
git clone https://github.com/dreamcity-rp/dc-apartments.git resources/[dc]/[others]/dc-apartments &&
git clone https://github.com/dreamcity-rp/dc-ambulancejob.git resources/[dc]/[activities]/[jobs]/[private]/dc-ambulancejob &&
git clone https://github.com/dreamcity-rp/dc-adminmenu.git resources/[dc]/[core]/dc-adminmenu &&
git clone https://github.com/dreamcity-rp/safecracker.git resources/[standalone]/safecracker &&
git clone https://github.com/dreamcity-rp/dpemotes.git resources/[standalone]/dpemotes