git clone https://github.com/dreamcity-rp/fivem-appearance.git [core]/fivem-appearance &&
git clone https://github.com/dreamcity-rp/dc-hud.git [core]/dc-hud &&
git clone https://github.com/dreamcity-rp/ox_fuel.git [core]/ox_fuel &&
git clone https://github.com/dreamcity-rp/dc-weathersync.git [core]/dc-weathersync &&
git clone https://github.com/dreamcity-rp/dc-spawn.git [core]/dc-spawn &&
git clone https://github.com/dreamcity-rp/dc-smallresources.git [others]/dc-smallresources &&
git clone https://github.com/dreamcity-rp/dc-skillbar.git [others]/dc-skillbar &&
git clone https://github.com/dreamcity-rp/dc-recyclejob.git [activities]/dc-recyclejob &&
git clone https://github.com/dreamcity-rp/dc-prison.git [others]/dc-prison &&
git clone https://github.com/dreamcity-rp/dc-policejob.git [activities]/[jobs]/[private]/dc-policejob &&
git clone https://github.com/dreamcity-rp/dc-multicharacter.git [core]/dc-multicharacter &&
git clone https://github.com/dreamcity-rp/dc-menu.git [core]/dc-menu &&
git clone https://github.com/dreamcity-rp/dc-management.git [core]/dc-management &&
git clone https://github.com/dreamcity-rp/dc-loading.git [core]/dc-loading &&
git clone https://github.com/dreamcity-rp/dc-interior.git [core]/dc-interior &&
git clone https://github.com/dreamcity-rp/dc-input.git [core]/dc-input &&
git clone https://github.com/dreamcity-rp/dc-core.git [core]/dc-core &&
git clone https://github.com/dreamcity-rp/dc-commandbinding.git [core]/dc-commandbinding &&
git clone https://github.com/dreamcity-rp/dc-cityhall.git [others]/dc-cityhall &&
git clone https://github.com/dreamcity-rp/dc-apartments.git [others]/dc-apartments &&
git clone https://github.com/dreamcity-rp/dc-ambulancejob.git [activities]/[jobs]/[private]/dc-ambulancejob &&
git clone https://github.com/dreamcity-rp/dc-adminmenu.git [core]/dc-adminmenu &&
git clone https://github.com/dreamcity-rp/safecracker.git [others]/safecracker &&
git clone https://github.com/dreamcity-rp/depemotes.git [others]/depemotes